### ISSUE TITLE
Button Component Resizing Issues

### ISSUE THREAD

**Issue by aalnussairi** [mondaycom/monday-ui-react-core#1111]
https://user-images.githubusercontent.com/25638617/218756344-d8ebac87-0acc-4ddb-acf0-f6e0c2df74c6.mp4

When I increase the frame size of a button that I have set to have a width of 100% in the styles prop of the Button component, it resizes correctly when increasing in size, but not the other way around.

Is this an issue with the [useResizeObserver](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/hooks/useResizeObserver.ts) hook?

**Comment by orrgottlieb** [comment]
Hi, @aalnussairi we will fix it, you are correct, this is an issue with the useResizeObserver, 
as a quick fix for now you can change the `key` prop

**Comment by Jilesh980** [comment]
hi @aalnussairi i can work and fix this issue, please assign to me.
Thank you

**Comment by talkor** [comment]
The `resizeObserver` was removed so this issue is now resolved in `v2.63.2`, thanks for reporting!
