### ISSUE TITLE
EditableHeading doesn't work while EditableInput does

### ISSUE THREAD

**Issue by Carduelis** [mondaycom/monday-ui-react-core#115]
```
// works fine
import EditableInput from "monday-ui-react-core/dist/EditableInput";
export default () => EditableInput value="Edit H2 tooltip" />
```

```
// throws an error
import EditableHeading from "monday-ui-react-core/dist/EditableHeading";
export default () => <EditableHeading value="Edit H2 tooltip" />
```

> index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

When I did a console.log of those components I got: 

![image](https://user-images.githubusercontent.com/3492820/116439167-890ac800-a84f-11eb-84bc-0490f368ebaa.png)

So looks like `EditableHeading` is not a React component, while `EditableInput` is.

Is there any workaround? Thank you

**Comment by Carduelis** [comment]
Update. Component `Heading` throws the same issue. Probably, it's the reason.

**Comment by orrgottlieb** [comment]
@Carduelis, thanks for opening the issue, I'm taking a look at it now

**Comment by SergeyRoyt** [comment]
I believe it was solved a long time ago - closing the issue
