### ISSUE TITLE
Button aria-expanded typo

### ISSUE THREAD

**Issue by Carduelis** [mondaycom/monday-ui-react-core#116]
There is a typo in the Button component: `aria-expended` instead of `aria-expanded`.
![image](https://user-images.githubusercontent.com/3492820/116536834-bb670480-a8e5-11eb-8b71-cbbcc1183b27.png)

"monday-ui-react-core": "^0.3.9",

**Comment by orrgottlieb** [comment]
@Carduelis thanks for reporting this issue, fixed from "0.3.10"

**Comment by Carduelis** [comment]
@orrgottlieb  thanks! That's awesomly fast reaction
