### ISSUE TITLE
ButtonGroup is not exported from the package

### ISSUE THREAD

**Issue by fikander** [mondaycom/monday-ui-react-core#117]
Please add 
`export { default as ButtonGroup } from "./ButtonGroup/ButtonGroup";`
to `src/index.js`

This prevents me from using it.

Tried to PR but repo is locked to contrib from outside.

**Comment by orrgottlieb** [comment]
@fikander thanks for opening an issue, we've fixed it now (since - 0.3.11).
We allow PR from a fork - I would love to speak with you and understand what went wrong if you want.

If it is relevant please email me at - orr at monday.com

**Comment by fikander** [comment]
Thanks for quick fix @orrgottlieb. Still in time to use it in devpost competition :)
`ButtonGroup` was the only problem I had.
I'll email you about unrelated ui-react-core question
