### ISSUE TITLE
Icon import not working with typescript

### ISSUE THREAD

**Issue by eidermaen** [mondaycom/monday-ui-react-core#1195]
I'm using `monday-ui-react-core@1.111.0` with typescript in my project.
When trying to import the Settings icon within a component (`import {Settings} from 'monday-ui-react-core/icons'`), I'm getting the following TS error: `TS2307: Cannot find module 'monday-ui-react-core/icons' or its corresponding type declarations.`.
When doing the exact same in a JS project (same monday-ui-react-core version), it is working just fine.

**Comment by hctuan** [comment]
Hi, you can do
```
const icons = require("monday-ui-react-core/icons");
const { Settings } = icons;
````
instead of
```
import {Settings} from 'monday-ui-react-core/icons'
```

**Comment by hctuan** [comment]
you can workaround
```
// @ts-ignore
import { Settings } from "monday-ui-react-core/icons";
```

**Comment by SergeyRoyt** [comment]
In the backlog: https://monday.monday.com/boards/3532714909/pulses/4318032345

**Comment by Yaronglp** [comment]
In case you do not want to use TS compiler directives like @ts-ignore, you can make the module readable by adding  a declaration-type file

create a new file and name it `monday-ui-react-core-icons.d.ts`
Inside that file put the following content:

```
declare module 'monday-ui-react-core/icons' {
  export const Settings: any;
}
```

**Comment by shlomitc** [comment]
this should be resolved in the latest version (2.x). if the issue still persists, please re-open
