### ISSUE TITLE
Incompatible with Next.js

### ISSUE THREAD

**Issue by Sawtaytoes** [mondaycom/monday-ui-react-core#1198]
Hi! I started a Next.js project today, installed the Monday.com SDK and the React-UI library (Vibe?).

I got an error:
> Global CSS cannot be imported from within node_modules.

This is shown in the console as:
```
wait  - compiling /_error (client and server)...
error - ./node_modules/react-dates/lib/css/_datepicker.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\monday-ui-react-core\dist\esm\src\components\DatePicker\DatePicker.js
```

Next.js says:
> Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
Source: https://nextjs.org/docs/messages/css-npm

I was wondering if you knew of a compatibility method. I'm trying to follow the guide in [your docs](https://developer.monday.com/apps/docs/quickstart-view), but I'm not using Create-React-App.

**Comment by orrgottlieb** [comment]
Hi @Sawtaytoes , can you please add a demo repo, or code snippets, `This normally happens when a package's source files are accidentally consumed, instead of the built package.` - this is weird as we compile the CSS code.

**Comment by Sawtaytoes** [comment]
I gave up on Next.js and switched to Vite. With Vite, I had one issue with `global` not being defined in my browser (not sure why something cared about `global` instead of `window` or `globalThis`), but fixing that, I got it working finally.
