### ISSUE TITLE
Calendar picker is deprecated

### ISSUE THREAD

**Issue by ThinhLe183** [mondaycom/monday-ui-react-core#1231]
Please switch to dayJs instead of momentJs which is deprecated and shouldn't be used anymore

**Comment by orrgottlieb** [comment]
Hi @ThinhLe183, it seems that the 3rd party (`react-dates`) that we are using for our date picker is using it, if you are not using this module, you won't need to install it

**Comment by ThinhLe183** [comment]
Hi @orrgottlieb, I've investigated react-dates, they're using Date not Moment as you said. I really want your team supports dayjs or at least Date

**Comment by orrgottlieb** [comment]
Which version did you check, they moved  from moment
