### ISSUE TITLE
Problem with BreadcrumbsBar.types

### ISSUE THREAD

**Issue by sergiodpino** [mondaycom/monday-ui-react-core#1237]
Hi all,

I've been trying to use the BreadcrumbsBar component, but I'm facing the following error.
![Captura de pantalla 2023-04-28 110612](https://user-images.githubusercontent.com/132058749/235118255-7cdafce6-b800-4380-9327-8dde6d3e0b0b.png)
From what we have researched, it seems like it's not throwing an error in the impl because it's setting a default value that has a correct type, but in the interface definition it is wrong, as you can see in the following screenshot.
![image (4)](https://user-images.githubusercontent.com/132058749/235119380-c9a2f5d0-800b-4759-89bd-bffe91467bf1.png)
There is a workaround, which is simply adding "as any" right after writing the type in the component, but it would be nice if this could be fixed soon.
Let me know if you need more input on this.
Thanks :)

**Comment by Yaronglp** [comment]
Hi @sergiodpino,
Why do u use ````typeof BreadcrumbsBarType```` and not  ````BreadcrumbsBarType````?
![image](https://github.com/mondaycom/monday-ui-react-core/assets/10623307/6f127908-be47-4b24-b6e7-677a3a8402de)

![image](https://github.com/mondaycom/monday-ui-react-core/assets/10623307/41a1b1d5-b203-4ada-a208-f6d41d7c7567)

**Comment by SergeyRoyt** [comment]
Hey, guys! @Yaronglp @sergiodpino 
Thanks for raising and helping with the issue!
We've fixed it in this PR https://github.com/mondaycom/monday-ui-react-core/pull/1522, it's released in version `2.31.4`
