### ISSUE TITLE
Is there any need for LinkComponent component?

### ISSUE THREAD

**Issue by dsvitnev** [mondaycom/monday-ui-react-core#1293]
While fixing #1292 , found out that [LinkComponent](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/storybook/components/link-component/link-component.jsx) looks like redundant and outdated for me. Besides, i'm not found any cases of it's suitable usage except for two pages from PR above.
<details>

<summary>Search of occurances in project file structure:</summary>
<img width="1437" alt="SCR-20230518-tijf" src="https://github.com/mondaycom/monday-ui-react-core/assets/29986501/81c6cd97-3cd4-482c-8d92-7c6819ec2fe3">

</details>

So maybe remove it?

**Comment by shlomitc** [comment]
if not used, I think it's safe to delete. Thanks!

**Comment by SergeyRoyt** [comment]
Closing this, cause we've moved the storybook components out to https://github.com/mondaycom/vibe-storybook-components
I've also created a task to delete the component https://monday.monday.com/boards/3532714909/pulses/5294606873 from there - it's awaiting cause it's a breaking change

Thanks for raising this @dsvitnev!
