### ISSUE TITLE
Group button looks weird when both buttons have tooltips (bug)

### ISSUE THREAD

**Issue by hadasfa** [mondaycom/monday-ui-react-core#130]
<img width="138" alt="Screen Shot 2021-05-24 at 13 09 06" src="https://user-images.githubusercontent.com/72390374/119332417-39be8880-bc91-11eb-810a-9ff79869c11c.png">
The bug occurs when the group has two buttons and each has a tooltip as in the following code example:
<img width="723" alt="Screen Shot 2021-05-24 at 17 11 46" src="https://user-images.githubusercontent.com/72390374/119360285-20c6cf00-bcb3-11eb-9656-3e7deb97243c.png">

**Comment by orrgottlieb** [comment]
@hadasfa fixed!
