### ISSUE TITLE
Initially loading prop on a button appears broken

### ISSUE THREAD

**Issue by uri-shmueli** [mondaycom/monday-ui-react-core#135]
When setting the loading prop to true (hardcoded/initially), we get an empty small box instead of a button with the loading animation

https://style.monday.com/?path=/story/components-button--loading

![image](https://user-images.githubusercontent.com/67226689/120496682-6f1c5200-c3c6-11eb-9be2-181913d4420c.png)

**Comment by adnansam110** [comment]
@uri-shmueli Can you assign this issue to me under hacktoberfest label ?

**Comment by talkor** [comment]
Hey @uri-shmueli, a bit late response but the Button now keeps its size when changing to a loading state, so this issue is resolved :) Thanks for reporting
