### ISSUE TITLE
Add right badge support for MenuItem

### ISSUE THREAD

**Issue by adirhaz1z** [mondaycom/monday-ui-react-core#141]
<img width="297" alt="Screen Shot 2021-06-07 at 20 29 21" src="https://user-images.githubusercontent.com/70204051/121063495-0f131a80-c7cf-11eb-8671-f465afb15860.png">
Add support to right badges in the MenuItem (For example New / Beta..)

**Comment by adirhaz1z** [comment]
Tagging you following our conversation, if it could be promoted ^
@hadasfa

**Comment by sudesh7447** [comment]
@adirhaz1z Please assign me this.

**Comment by SergeyRoyt** [comment]
Was already solved
