### ISSUE TITLE
Add image support for MenuItem

### ISSUE THREAD

**Issue by adirhaz1z** [mondaycom/monday-ui-react-core#142]
It could be the same like component in MenuButton

**Comment by adirhaz1z** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/70204051/176441101-2eb98d3b-2e94-4e2d-a552-f8453411daa4.png">

**Comment by Dawood-Shahid** [comment]
Hay @adirhaz1z, will you provide the SVG icons or I say assets?

**Comment by sudesh7447** [comment]
@Dawood-Shahid Please assign me this.

**Comment by sosdan73** [comment]
As far as I understand, this issue is resolved. Should it be closed then?

**Comment by talkor** [comment]
Yes already resolved, thanks for pointing that up @sosdan73! Closing
