### ISSUE TITLE
chore: < GridKeyboardNavigationContext / >, useGridKeyboardNavigationContext - migrate to Typescript

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1568]
Typescript migration guideline https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

**Comment by shohan2001** [comment]
Can I take this up?

**Comment by SergeyRoyt** [comment]
Sure, we'd appreciate that!
@shohan2001

**Comment by Mehdy922** [comment]
can I work on it?

**Comment by SergeyRoyt** [comment]
Closed independently by @SergeyRoyt
