### ISSUE TITLE
fix: <BreadcrumbsBar> - shouldn't be clickable when type = Indication

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1569]
Items should be clickable only if type = Navigation

**Comment by lazyMonk1010** [comment]
hey SegeyRoyt!! I want to work on this issue.

**Comment by SergeyRoyt** [comment]
Hey, @lazyMonk1010!
The issue is assigned to you, thanks! 🙂

**Comment by SoumyadiptoPal** [comment]
@SergeyRoyt is this issue still open? I want to work on it.

**Comment by Kritik-J** [comment]
@SergeyRoyt If it's still addressable, I would like to work on it

**Comment by SergeyRoyt** [comment]
@SoumyadiptoPal assigned the issue to you, if you are still interested

**Comment by Aady7** [comment]
Is this isue still open? Would like to work on it.

**Comment by SergeyRoyt** [comment]
Issue is resolved by @SoumyadiptoPal ! Lots of thanks!
