### ISSUE TITLE
fix: <MenuDivider/ > - add padding

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1571]
Add 8px right and left padding to the menu divider

Current:
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/80303bca-9f2e-498b-9f60-7d12921a1007)

Expected:
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/f04c579d-93e9-4925-8ed0-330b352907af)

**Comment by joshijoe05** [comment]
Hello,
I would like to work on this issue. Can you assign this task to me?

**Comment by SergeyRoyt** [comment]
> Hello, I would like to work on this issue. Can you assign this task to me?

Go ahead with it, @joshijoe05!😉

**Comment by joshijoe05** [comment]
Hey @SergeyRoyt !
Can you provide steps to start the server and the port number?

**Comment by YossiSaadi** [comment]
Hey @joshijoe05!
Did you run `npm i`?

**Comment by Arnav7107** [comment]
Hey @SergeyRoyt I would love to contribute to this issue. Can you please assign this task to me?

**Comment by SergeyRoyt** [comment]
Hey, @joshijoe05 !
How is it going? You are willing to finish the issue? Need any help with that?

**Comment by joshijoe05** [comment]
@SergeyRoyt
Even though I run npm i
Later, when I run npm run storybook, it is saying the command is not recognised

**Comment by SergeyRoyt** [comment]
> @SergeyRoyt Even though I run npm i Later, when I run npm run storybook, it is saying the command is not recognised

@joshijoe05 Are you sure you are running the commands from the project root? 
Maybe dependencies installation process somehow went wrong... From the project root try to run 
`rm -rf node_modules && npm i && npm run storybook`

**Comment by joshijoe05** [comment]
Sure, I'll try this

**Comment by joshijoe05** [comment]
I tried but still saying the same !

**Comment by SergeyRoyt** [comment]
@SoumyadiptoPal please, write something under this issue - I can't assign you to it otherwise
