### ISSUE TITLE
fix: <Avatar> remove default tabIndex = 0

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1572]
Set default value of tabIndex equal to zero only if avatar is clickable or has a tooltip (please check this page https://style.monday.com/?path=/docs/media-avatar-avatar--avatar-with-tooltip)

Example of the issue - `ListItem`
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/2a586d1b-5312-452b-9992-6175dfd55cb4)

**Comment by Kritik-J** [comment]
@SergeyRoyt please assign this to me

**Comment by SergeyRoyt** [comment]
Thanks a lot, @Kritik-J !
