### ISSUE TITLE
feat: <AttentionBox> closeButton - hide tooltip, add prop for configuring ariaLabel

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1573]
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/e2e909a1-0bc0-4643-9085-21276e7acf36)

Hide tooltip for the close button, and add a prop `closeButtonAriaLabel` with default value = `Close` for e.g. translating this ariaLabel

**Comment by Kritik-J** [comment]
@SergeyRoyt, I would like to work on it. Please assign this to me

**Comment by SergeyRoyt** [comment]
Great job! :)
