### ISSUE TITLE
docs: replace all <a/> tags with <Link/> in stories

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1575]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5231383026)

- In `preview.js` replace `LinkComponent` with `Link` from `vibe-storybook-components`
- Remove redundant `<a>` props, if needed adjust them with needed `Link` params
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/bc298345-2334-4386-905b-012b91e5b00a)

**Comment by SergeyRoyt** [comment]
Thanks, @sulavghimiree!
Assigned to you ;)

**Comment by prakashAditya639** [comment]
@SergeyRoyt Sorry for solving a issue which is not assigned to me but it's been assigned three days ago , Please review my PR Sir

**Comment by prakashAditya639** [comment]
@SergeyRoyt Can you please tell me that what is the significance of withoutSpacing you added in Link Tag

**Comment by SergeyRoyt** [comment]
@prakashAditya639 sure! Link component adds spacing around itself by default, which in this specific case leads to double spacing - cause the text before and after it also adds spaces
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/056f0826-c9ec-419a-a16a-8082d9de007d)

The other solution would be to remove `{" "}` before and after the Link

**Comment by ansumanswain** [comment]
on it.

**Comment by evadrake89** [comment]
@SergeyRoyt Sir i am @prakashAditya639 I have fixed all your issues but from another account please review my pr

**Comment by SergeyRoyt** [comment]
The issue is resolved
Thanks a lot, @evadrake89!
