### ISSUE TITLE
tests: <EditableHeading> interaction tests

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1576]
Add storybook interactions tests for `EditableHeading` component - check https://github.com/mondaycom/monday-ui-react-core/blob/master/TESTING_README.md for guidelines

**Comment by jes14** [comment]
Hi, Can I start this issue?

**Comment by SergeyRoyt** [comment]
Glad to see you here again, @jes14 ! ^_^
You are most welcome to!

**Comment by SergeyRoyt** [comment]
The issue is resolved!
Thanks a lot for solving it @jes14!
