### ISSUE TITLE
docs: <Checkbox> Usage guidelines - fix font

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1577]
Fix font in the first usage - should be the same as everywhere else
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/566152bc-ca05-4778-a3c6-7aa6d28fbde6)

Probably include `vibe-text` is missing in the custom class

**Comment by AlisanCavus** [comment]
I would like to work on it.

**Comment by SergeyRoyt** [comment]
Thanks, @AlisanCavus ! It's yours ;)

**Comment by Krishnakalani111** [comment]
If it's still addressable i would like to work on it

**Comment by SergeyRoyt** [comment]
Thanks for the contribution, @SoumyadiptoPal!
Will assign the issue to you, once you write smth here
