### ISSUE TITLE
docs: <Combobox> tip links spacing fix

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1578]
`Combobox` component:
https://style.monday.com/?path=/docs/inputs-combo-box--overview

Add spaces between link and ().

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/7d68ed49-be66-462f-bff5-7186e2834636)

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue. Could you assign it to me?

**Comment by talkor** [comment]
> I'd like to work on this issue. Could you assign it to me?

Hey, @anirudhsudhir!
Assigned to you, thanks! 🙂

**Comment by SergeyRoyt** [comment]
Resolved! Thanks!
