### ISSUE TITLE
docs: add missing link to component - <Menu> page

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1579]
Using `Link` component from `vibe-storybook-components`

https://style.monday.com/?path=/docs/navigation-menu-menu--overview

Do's and Don'ts
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/62d9db13-8783-4267-bf3a-b26bce9cb795)

**Comment by SarthakD15** [comment]
Hey Sergey, Can I work on this issue ?

**Comment by SergeyRoyt** [comment]
Hey, @SarthakD15!
Assigned it to you :)

**Comment by SarthakD15** [comment]
Thanks @SergeyRoyt :)

**Comment by SarthakD15** [comment]
Hey @SergeyRoyt, I have resolved the issue but I am finding trouble testing it locally.
Can you please guide me what exactly need to be done to run and check it on localhost ?

**Comment by AnuMessi10** [comment]
Let me know if this issue needs to be addressed, I can look into it.

**Comment by SarthakD15** [comment]
#1608 
Hey @SergeyRoyt, I have solved the issue and made a PR.
Please review the above PR :)
Thanks :)

**Comment by SergeyRoyt** [comment]
Issue is resolved, thanks @SarthakD15! 💪
