### ISSUE TITLE
docs: Accessibility page - fix links

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1580]
https://style.monday.com/?path=/docs/foundations-accessibility--page

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/01a8fdbe-442a-48c4-aad1-4b644c46b4ac)

- [ ] Fix link size
- [ ] Fix link spacing

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/8138f266-16a8-44b1-bcdd-6d03908b9bb8)

- [ ] Fix link size
- [ ] Fix link spacing

**Comment by AnuMessi10** [comment]
Hi @SergeyRoyt, let me know if this still needs to be addressed, I would like to look into it.

**Comment by SergeyRoyt** [comment]
> Hi @SergeyRoyt, let me know if this still needs to be addressed, I would like to look into it.

Thanks, @AnuMessi10 ! I believe it's gonna be solved by @Dhoni77, but you are welcome to take any other vacant task and I'll try to add more tasks today 🙏

**Comment by SergeyRoyt** [comment]
Thanks for the contribution, @Dhoni77 !
The issue is resolved
