### ISSUE TITLE
docs: fix text in a few places

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1583]
- https://style.monday.com/?path=/docs/inputs-dropdown--overview - remove subtitle
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/1ef41864-7886-4859-8d58-d874c84f9ed5)
- Change "More item" to "Menu item"
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/b8cab00c-40b1-48ab-a7fe-5ef98a73c205)
- https://style.monday.com/?path=/docs/foundations-typography--page - change "ui" to be "UI"

**Comment by Vijeth56** [comment]
I would like to contribute to this issue.
Please assign this to me.

**Comment by SergeyRoyt** [comment]
> I would like to contribute to this issue. Please assign this to me.

Thanks, @Vijeth56! It's yours!

**Comment by SergeyRoyt** [comment]
Thanks, @Vijeth56 !
