### ISSUE TITLE
docs: enable controls for some of the stories

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1587]
Controls in the storybook allows you to change the props of the component rendered in the story directly in `ArgsTable`, it looks like this
<img width="1022" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/2aa5fc6a-9652-4c3b-b682-3ae992925021">

However some components doesn't have controls enabled rn
<img width="1047" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/a9313b12-587c-4187-8dfb-28a71b0f020e">

`ArgsTable` for correctly enabled controls will look like this `<ArgsTable story="Overview" />`
and without controls it looks like this `<ArgsTable of={ Label } />`

Need to go over these components and enable controls for them and check if it's working correctly
<img width="811" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/fe8ac26e-cce4-432e-8cac-5e83a03a41ae">

enums, icons and actions handling will be fixed in a separate issue

**Comment by Dhoni77** [comment]
Hi @SergeyRoyt  can u assign me this issue

**Comment by SergeyRoyt** [comment]
> Hi @SergeyRoyt can u assign me this issue

Thanks, @Dhoni77 ! Assigned to you ;)

**Comment by SergeyRoyt** [comment]
Great job, thanks a lot!! 👑
