### ISSUE TITLE
feat: make <Label> a VibeComponent and add ref forwarding

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1588]
Instead of `FC` make `Label` be an instance of a `VibeComponent` and forward ref to it via `useMergeRefs` hook - see other components as an example, e.g. `Chips`

**Comment by jes14** [comment]
Hi, Can I start this issue?

**Comment by SergeyRoyt** [comment]
Thanks, @jes14! It's yours ;)

**Comment by SergeyRoyt** [comment]
Thanks a lot @jes14!
