### ISSUE TITLE
Error Log Message in Storybook for label Component

### ISSUE THREAD

**Issue by jes14** [mondaycom/monday-ui-react-core#1605]
Dear Monday Team,

I would like to report an issue that I encountered while using Storybook. Specifically, when working with the "label(data-display-label--overview)" component, I noticed the presence of an error message in the log.

Thank you!

<img width="1004" alt="Screenshot 2023-10-04 at 09 04 56" src="https://github.com/mondaycom/monday-ui-react-core/assets/23358657/bafeba99-32df-413a-9219-e49e30291e0f">

**Comment by SergeyRoyt** [comment]
Thanks a lot, @jes14! We'll look into that ;)

**Comment by darshk07** [comment]
@SergeyRoyt Can you assign this task to me, if it's still unhandled right now? I might be able to solve this.

**Comment by SergeyRoyt** [comment]
Hey, @darshk07 ! 
We'd appreciate your help a lot on this issue! 🙏

**Comment by viditagrawal56** [comment]
Hey @darshk07 Did you find what's causing the warning?

**Comment by darshk07** [comment]
> Hey @darshk07 Did you find what's causing the warning?

Hey, no I'm not able to resolve it actually.

**Comment by viditagrawal56** [comment]
@darshk07 Oh ok, I tried too but I couldn't find anything 😅

**Comment by darshk07** [comment]
@SergeyRoyt You can unassign me from this. I might not be the right guy for this. Thanks.

**Comment by RitikBora** [comment]
Hello @SergeyRoyt  ,
Is this fixed?
@jes14 i'm unable to reproduce the issue. On my end I dont see the particular console error you shared. Did you change the label with any of the controls available to get this console error?

**Comment by talkor** [comment]
Thanks @jes14 for opening the issue and thanks @RitikBora, I can't reproduce it either, even after changing some controls, so closing for now. @jes14 if the issue still happens please comment with steps so we'll be able to fix it properly. Thanks!
