### ISSUE TITLE
docs: < Link /> use cases-Shortening texts - add space before the link

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1606]
[Monday ticket link](https://monday.monday.com/boards/3532714909/pulses/4786031991)

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/b098bd73-56b0-4648-91ab-80ac03081e91)

https://style.monday.com/?path=/docs/navigation-link--overview

**Comment by Kritik-J** [comment]
please assign this to me

**Comment by SergeyRoyt** [comment]
Thanks, @Kritik-J! U got it :)

**Comment by SergeyRoyt** [comment]
Thanks for the contribution, @Kritik-J ! 💪
The issue is resolved
