### ISSUE TITLE
feat: <AttentionBox> change default icon for Primary type to Info icon

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1607]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5075672010)

Currently `AttentionBox` have a default icon = `AlertIcon`
<img width="362" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/8e38cc64-295f-41a1-979e-e8d05e846dc7">

We want to replace it with `Info` icon, but only when `type` is `primary`:
<img width="389" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/a521aa4c-75f8-46b5-bdfb-dfb0be31d62f">

**Comment by Kritik-J** [comment]
@SergeyRoyt please assign this to me

**Comment by SergeyRoyt** [comment]
You got it, champ! ;)

**Comment by SergeyRoyt** [comment]
Issue solved!
Thanks a lot, @Kritik-J!
