### ISSUE TITLE
chore: fix Github actions lint warnings - < AvatarGroup />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1629]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5299782444)

Two errors related to `AvatarGroup` that we have in each PR, e.g. here https://github.com/mondaycom/monday-ui-react-core/pull/1624/files
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/b9eb37e8-3bc5-4e84-8542-9366e7523f93)

**Comment by Kritik-J** [comment]
@SergeyRoyt  I would like to work on it, Please assign this to me

**Comment by SergeyRoyt** [comment]
Very cool! Thanks for the contribution, @Kritik-J!
