### ISSUE TITLE
chore: fix Github actions lint warnings - < Button />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1631]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5299840268)

2 errors related to `Button` that we have in each PR, e.g. here https://github.com/mondaycom/monday-ui-react-core/pull/1624/files

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/0c0e5b08-70fe-4333-9395-3ff991026269)

**Comment by Kritik-J** [comment]
@SergeyRoyt I would like to work on it, Please assign this to me

**Comment by SergeyRoyt** [comment]
You got it, @Kritik-J! 💪

**Comment by SergeyRoyt** [comment]
Good job! Thanks for the contribution, champ! 😃
