### ISSUE TITLE
chore: fix Github actions lint warnings - < AlertBanner />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1632]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5299864727)

2 errors related to `AlertBanner` tests that we have in each PR, e.g. here https://github.com/mondaycom/monday-ui-react-core/pull/1624/files

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/598548e1-05d8-4956-862d-78a3cb5b8405)

**Comment by shelar1423** [comment]
Hey i would like to work on this, but i need some guidence

**Comment by Dhoni77** [comment]
I would like to take this up

**Comment by SergeyRoyt** [comment]
Nice! Thank you!
