### ISSUE TITLE
chore: fix Github actions lint warnings - < ColorPicker />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1641]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5305880708 )

4 errors related to `ColorPicker` that we have in each PR, e.g. here https://github.com/mondaycom/monday-ui-react-core/pull/1640/files

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/594951b3-858a-449d-9509-2130e5e5d268)

**Comment by Kritik-J** [comment]
@SergeyRoyt I would like to work on it, Please assign this to me

**Comment by SergeyRoyt** [comment]
Thanks for the contribution @Kritik-J! 👑
