### ISSUE TITLE
feat: provide props for ariaLabel - < AvatarGroupCounter />, < TableHeaderCell />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1644]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5305989615)

Provide ariaLabel props to override corresponding ariaLabel for i18n purposes
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/3146f7c7-954d-469f-bc69-b02b351ed8b8)

- `AvatarGroup` should have one new ariaLabel prop - `counterAriaLabel`. If it's undefined than it should be equal to the default values which it have now in both of the cases
- `TableHeaderCell` should have a prop called `sortButtonAriaLabel`

**Comment by Kritik-J** [comment]
@SergeyRoyt I would like to work on it, Please assign this to me

**Comment by SergeyRoyt** [comment]
Issue resolved
Thanks a lot @Kritik-J ! 👑
