### ISSUE TITLE
chore: resolve lint warnings - < Menu />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1648]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5311541029)

<img width="923" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/ffd37a2f-ce28-4ba9-ac83-e97ab9b68f47">

**Comment by Kritik-J** [comment]
@SergeyRoyt Please assign this to me

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J !
