### ISSUE TITLE
chore: resolve lint warnings - < Tipseen />, < Tooltip />, < TypographyHooks />, < VirtualizedList />, < VirtualizedGrid />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1650]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5311575773)

<img width="941" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/edcd57b9-df30-48ec-b899-0fd9b35b8212">

**Comment by Dhoni77** [comment]
Hi @SergeyRoyt I would like to work on this

**Comment by SergeyRoyt** [comment]
Hey!
Thank you! It's yours ;)

**Comment by SergeyRoyt** [comment]
Closed thanks to @Dhoni77 !
