### ISSUE TITLE
fix: < ColorPicker /> indicator is dissapearing when color is selected

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1655]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/4315569094)

https://style.monday.com/?path=/docs/pickers-colorpicker--with-indicator

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/c73d0498-67d9-4ba9-9733-504c4c702fed)
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/efc87811-4db9-4c61-9645-e8f028af11ac)

**Comment by sayyedarib** [comment]
Hey, I would like to work on this issue , can you please assign this to me?

**Comment by SergeyRoyt** [comment]
Hey, @sayyedarib !
Thanks! You got it!

**Comment by SergeyRoyt** [comment]
Issue is resolved, all thanks to @sayyedarib !
