### ISSUE TITLE
fix: < ProgressBar /> sizes static prop - TS error

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1661]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5331834906)

Throws this error in TS projects
<img width="1386" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/f50e30b0-7685-40d7-81f2-8fceb8607e24">

hint: 
- create TS project, e.g. via create-react-app
- look into other components which are using same `SIZES` object, try if the issue repeats

**Comment by viditagrawal56** [comment]
Hey @SergeyRoyt I think I found a fix, maybe.

In LinerProgressBar.d.ts the type if size is defined as typeof SIZES which I think is the problem.
Changing it to size?: SIZES should fix it!

ScreenShots: 

Before ->

![image](https://github.com/mondaycom/monday-ui-react-core/assets/52532308/e83883a2-3144-4569-8269-06158eccc6f0)

After ->

![image](https://github.com/mondaycom/monday-ui-react-core/assets/52532308/4055dc97-b876-4336-bd31-20649e6854de)

If I am right assign me this issue would love to work on it! 😄

**Comment by SergeyRoyt** [comment]
From what I see e.g. in `ListItem` which is also using `SIZES`  - the type should be declared like this: 
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/e786ef00-d5f4-4843-8182-05c3b394f869)
So, probably it should be like this.

To simplify the code you can also extract `export type Size = typeof SIZES[keyof typeof SIZES]` into the file where `SIZES` are declared. Same thing done already in `IconButton`, so you can check it out and refactor the code there too. But this refactoring is completely optional in the scope of this task 🙏

You can always check your solution by packing the package and testing it in typescript project
To pack the package with your changes you can do this: `npm run build && npm pack`, this will create an archive in your project root folder, which you later can install into your typescript create-react-app test app - there you can check if TS is not throwing any errors and that the types are exported correctly

**Comment by viditagrawal56** [comment]
Hey @SergeyRoyt,
While proposing the previous solution I looked at the Loader component which also uses the SIZES property and the type was declared as size?: SIZES.

That said the approach you suggested is ultimately the better one.
Will start working on it ASAP! 😊

**Comment by SergeyRoyt** [comment]
@viditagrawal56 Loader is a bit different, it's using enum instead of just object
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/50e9414c-f21b-4744-b581-679e6224935c)
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/715003d0-0eda-4694-b7cb-1496afef861b)

**Comment by viditagrawal56** [comment]
@SergeyRoyt Oops missed that!😬

**Comment by viditagrawal56** [comment]
Hey @SergeyRoyt I am getting the following error while running npm build

![image](https://github.com/mondaycom/monday-ui-react-core/assets/52532308/e382d665-a068-44bf-b518-1533587ce2a2)

I tried changing the " build:storybook-exports: ./scripts/build-storybook-exports.js, " to " build:storybook-exports: scripts/build-storybook-exports.js, " but it didnt work either.

I confirmed that scripts folder does exist in the root directory and searched the fix for the issue but I couldn't find one.

I have made the necessary changes in LinearProgressBars size props but wasn't able to test it because build failed.

Can you please help me 🙏

**Comment by viditagrawal56** [comment]
@SergeyRoyt I have made a draft pr of the changes I made let me know if you need any more changes!

**Comment by SergeyRoyt** [comment]
> Hey @SergeyRoyt I am getting the following error while running npm build
> 
> ![image](https://user-images.githubusercontent.com/52532308/275538117-e382d665-a068-44bf-b518-1533587ce2a2.png)
> 
> I tried changing the " build:storybook-exports: ./scripts/build-storybook-exports.js, " to " build:storybook-exports: scripts/build-storybook-exports.js, " but it didnt work either.
> 
> I confirmed that scripts folder does exist in the root directory and searched the fix for the issue but I couldn't find one.
> 
> I have made the necessary changes in LinearProgressBars size props but wasn't able to test it because build failed.
> 
> Can you please help me 🙏

Weird. And you are running it from the root project folder, right? Not sure why
Is it Windows? Maybe that's why

Nvm, I'll test b my our own. But looks good so far

**Comment by viditagrawal56** [comment]
> > Hey @SergeyRoyt I am getting the following error while running npm build
> > ![image](https://user-images.githubusercontent.com/52532308/275538117-e382d665-a068-44bf-b518-1533587ce2a2.png)
> > I tried changing the " build:storybook-exports: ./scripts/build-storybook-exports.js, " to " build:storybook-exports: scripts/build-storybook-exports.js, " but it didnt work either.
> > I confirmed that scripts folder does exist in the root directory and searched the fix for the issue but I couldn't find one.
> > I have made the necessary changes in LinearProgressBars size props but wasn't able to test it because build failed.
> > Can you please help me 🙏
> 
> Weird. And you are running it from the root project folder, right? Not sure why Is it Windows? Maybe that's why...
> 
> Nvm, I'll test b my our own. But looks good so far

Yeah I made sure I was running it from the root project folder. You can see it in the following screenshot.

![image](https://github.com/mondaycom/monday-ui-react-core/assets/52532308/92366ea4-1ba6-4465-9d96-b9e3233dbdef)

And yes I am running this on a windows machine.

**Comment by viditagrawal56** [comment]
@SergeyRoyt So do you want me to make any changes?
If not then should I make the actual pr?

**Comment by SergeyRoyt** [comment]
@viditagrawal56 issue is resolved, all thanks to you! 👑
