### ISSUE TITLE
fix: < Tipseen /> - delay functionality isn't working

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1672]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/3709336002)

**Comment by AaronTJDev** [comment]
Hi @SergeyRoyt , I'd like to take this one. Can you share the ticket details here? I'm not able to access it.

**Comment by SergeyRoyt** [comment]
Hey, @AaronTJDev!
Tried to reproduce this one and didn't succeed. Investigating, but maybe this issue will be closed

https://github.com/mondaycom/monday-ui-react-core/assets/104433616/3d0bf090-e5bf-4354-9cab-88c152011768

**Comment by SergeyRoyt** [comment]
Not reproducible - closing
