### ISSUE TITLE
fix: < Text / > - when more than one row ellipsis is applied - the tooltip doesn't show

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1673]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5070129086)

https://style.monday.com/?path=/docs/text-text--overflow

**Comment by viditagrawal56** [comment]
Hey @SergeyRoyt I was looking into the codebase to see if I could find a fix for this issue, and I think i found one.

![image](https://github.com/mondaycom/monday-ui-react-core/assets/52532308/57b97cf4-b3ca-43ee-8729-b4dd2be51f04)

In the function useTooltipProps, the ignoreHeightOverflow is set to true, as shown in the above screenshot.
From what I understand ignoreHeightOverflow ignores the vertical oveflow of the text inside the Text component which I think is the issue.
So setting the ignoreHeightOverflow to false should resolve the error I think.
Am I missing something, or the solution is as simple as setting the ignoreHeightOverflow flag to false?

**Comment by SoumyadiptoPal** [comment]
I want to work on this issue. Please assign this to me!!

**Comment by viditagrawal56** [comment]
> Hey @SergeyRoyt I was looking into the codebase to see if I could find a fix for this issue, and I think I found one.
> 
> ![image](https://user-images.githubusercontent.com/52532308/276364483-57b97cf4-b3ca-43ee-8729-b4dd2be51f04.png)
> 
> In the function useTooltipProps, the ignoreHeightOverflow is set to true, as shown in the above screenshot. From what I understand ignoreHeightOverflow ignores the vertical overflow of the text inside the Text component which I think is the issue. So setting the ignoreHeightOverflow to false should resolve the error I think. Am I missing something, or the solution is as simple as setting the ignoreHeightOverflow flag to false?

@SergeyRoyt

**Comment by viditagrawal56** [comment]
@SergeyRoyt Ok I'll give it a try :)

**Comment by viditagrawal56** [comment]
Hey @SergeyRoyt Just wanted to confirm that I am on the right track.....

1.   I need to create a new context say `TextContext` with `ignoreHeightOverflow` set to `false` and export it from a new file say 
`TextContext.ts` which is placed in a new folder `utils` inside the root `Text` component folder.

2.   After that import the context in `Text.tsx` and wrap the `Typography` component inside the code with `<TextContext.Provider value={{ updateFocusedItem }}>`

Am I on the write track or am I missing something?

**Comment by viditagrawal56** [comment]
> Hey @SergeyRoyt, Just wanted to confirm that I am on the right track.....
> 
> 1. I need to create a new context say `TextContext` with `ignoreHeightOverflow` set to `false` and export it from a new file say
>    `TextContext.ts` which is placed in a new folder `utils` inside the root `Text` component folder.
> 2. After that import the context in `Text.tsx` and  initialize ignoreHeightOverflow by `const { ignoreHeightOverflow } = useContext(TextContext);`
> 3. Then  wrap the `Typography` component inside `Text.tsx` with `<TextContext.Provider value={{ ignoreHeightOverflow }}>`
> 
> Am I on the right track or am I missing something?

@SergeyRoyt

**Comment by SergeyRoyt** [comment]
Closed thanks to @viditagrawal56 !
