### ISSUE TITLE
feat: < AvatarGroup / > - the component contains padding that shouldn't be part of it

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1674]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/4570623896)

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/1fc93baa-53a5-4b9d-95da-b918c44a7a21)

https://style.monday.com/?path=/docs/media-avatar-avatargroup--overview

**Comment by nabinbhatt** [comment]
@SergeyRoyt please assign this issue to me

**Comment by shlomitc** [comment]
Just be aware that this is a breaking change and in such case should be introduced as a new prop the when turned on will remove the padding. Consider also logging this as a something that will become default in the upcoming major version

**Comment by viditagrawal56** [comment]
Hey @SergeyRoyt As the assignee has not made a PR since 3 days, can you assign me this issue?

**Comment by nabinbhatt** [comment]
Hello @viditagrawal56 thanks for the reminder :)

**Comment by SergeyRoyt** [comment]
Closed thanks to @nabinbhatt !
