### ISSUE TITLE
fix: < Toast /> close button - replace < Button /> and < Icon /> with < IconButton />

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1675]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5299566907)

<img width="857" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/d6f2822a-97ae-4035-a713-fe97ccb89231">

**Comment by Kritik-J** [comment]
@SergeyRoyt please assign this to me

**Comment by SergeyRoyt** [comment]
You got it, @Kritik-J ! 🙂
Thanks!

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J !
