### ISSUE TITLE
fix: < ComboBox / > - change stickyCategories to not be the default behavior

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1676]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/4247402438)

Categories are always sticky, though by default (without `stickyCategories` prop) they shouldn't be

**Comment by Kritik-J** [comment]
@SergeyRoyt please assign this to me

**Comment by SergeyRoyt** [comment]
It's yours @Kritik-J ! Thanks!

**Comment by Kritik-J** [comment]
@SergeyRoyt Could you please provide more details?

**Comment by SergeyRoyt** [comment]
Hey, @Kritik-J !
So, in this story https://style.monday.com/?path=/docs/inputs-combo-box--with-categories, `Regular` combobox is working exactly like `Sticky mode` and that's the issue. Regular Combobox categories should be normally scrollable, sticky categories should work only if `stickyCategories` props is true
P.S. also needed to change the story itself, so `Sticky mode` will have `stickyCategories`

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J !
