### ISSUE TITLE
feat: < Dialog /> should throw console.error if containerSelector is not found

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1679]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5350072279)

**Comment by arianxq** [comment]
Hi, I would like to work on this.

**Comment by SergeyRoyt** [comment]
Hey, @arianxq !
Thanks, good luck with that!

**Comment by Kritik-J** [comment]
@SergeyRoyt As the assignee has not created a PR since last week, can you assign me this issue?

**Comment by arianxq** [comment]
@Kritik-J
I had intended to work on this issue, but I see that you've already submitted a pull request. In light of that, I respect your efforts and contributions, you can take this issue. Best of luck with your PR!

**Comment by SergeyRoyt** [comment]
Closed thanks to @Kritik-J !

Sorry, @arianxq 🙏
