### ISSUE TITLE
feat: < TextField /> add red asterisks(*) when required=true

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1697]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/5005547320)

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/dfb88e1f-44a1-47f2-8f6b-2695c29cc70f)

To avoid making breaking changes, let's wrap this ability with separate prop `requiredAsterisk`, which will be `false` by default. Write following TODO comment - `deprecate in next major`. Add required story example to variants here https://style.monday.com/?path=/docs/inputs-textfield--overview with `requiredAsterisk=true`

**Comment by HarshitVashisht11** [comment]
Can you assign this issue to me, ican fix this issue

**Comment by SergeyRoyt** [comment]
Hey, @HarshitVashisht11 !
It's yours, thanks!

**Comment by Hossein-Mirazimi** [comment]
@SergeyRoyt 
Is this issue still open?

**Comment by SergeyRoyt** [comment]
Hey, @Hossein-Mirazimi!
Sorry, this task is already assigned to someone, but you are more than welcome to contribute to any other vacant issue. If you don't find anything interesting for you here, make sure to check out also issues in this repo https://github.com/mondaycom/vibe-storybook-components/issues

**Comment by Hossein-Mirazimi** [comment]
@SergeyRoyt 

thanks a lot :+1: 

I will check these issues

**Comment by SergeyRoyt** [comment]
Closed thanks to @HarshitVashisht11 !
