### ISSUE TITLE
<Dropdown /> border focus color doesn't respect <ThemeProvider /> primary color

### ISSUE THREAD

**Issue by Andrew-Zakharov** [mondaycom/monday-ui-react-core#1767]
We're early adopters of product theming with `ThemeProvider`. Everything works great so far, but `<Dropdown />` border color on focus seems to use wrong token:
now - `var(--color-basic_blue)`
probably should be - `var(--primary-color)` (at least other inputs use it)

https://github.com/mondaycom/monday-ui-react-core/assets/108681710/5c931857-f3c6-4557-8003-904871a7e1a1

<img width="1728" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/108681710/4547c930-e5ef-4acc-8d99-a9e6e063cff1">

**Comment by SergeyRoyt** [comment]
Hey @Andrew-Zakharov !
Thanks a lot for the feedback and for raising the issue, we appreciate it! ^_^
The issue is closed now, `Dropdown` border color on focus should have `primary-color` starting from version `2.64.2`
