### ISSUE TITLE
docs: RelatedComponents - <Icon> component example

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1780]
[The task is relevant for external contributors]
[(Monday ticket)](https://monday.monday.com/boards/3532714909/pulses/5506787935)

- Add [Icon](https://style.monday.com/?path=/docs/media-icon--overview) component example to `COMPONENTS_DESCRIPTIONS_ENTRIES` array so it'd appear on [components catalog page](https://style.monday.com/?path=/docs/catalog--catalog)
- Add "links" to the related component on following pages
  - On [IconButton](https://style.monday.com/?path=/docs/buttons-iconbutton--overview) page replace `ButtonGroup` reference with `Icon`

Example of Related Components section
<img width="1080" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/9120de4e-808d-4ee6-adab-098b261eb4fe">

**Comment by SergeyRoyt** [comment]
Hey, @Dhoni77! 
Glad to see you here again! ;)
Thanks, champ, it's yours! 💪

**Comment by Dhoni77** [comment]
Hey @SergeyRoyt can you provide a little more description on what needs to be done ?
I cannot find the button group reference in IconButton

**Comment by SergeyRoyt** [comment]
Hey, @Dhoni77 !
Sure, what I meant about the `ButtonGroup` reference on `IconButton` page is this one 
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/e87814eb-6875-4d91-8ad6-67289296dac9)
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/3decfdcb-0b3c-4a79-80d7-a8eb8e10e835)

The task it so create a new RelatedComponent example for the Icon component and add a reference to it on the `IconButton` page instead of `ButtonGroup`.
As an component for RelatedComponent example you can take component from the Icon overview story

You can also take a look at this PR as a reference https://github.com/mondaycom/monday-ui-react-core/pull/1806

**Comment by Dhoni77** [comment]
Thanks @SergeyRoyt 👍
