### ISSUE TITLE
docs: RelatedComponents - <VirtualizedGrid> component example

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1810]
[The task is relevant for external contributors]
[(Monday ticket)](https://monday.monday.com/boards/3532714909/pulses/5506803919)

- Add [VirtualizedGrid](https://style.monday.com/?path=/docs/navigation-virtualizedgrid--docs) component example to `COMPONENTS_DESCRIPTIONS_ENTRIES` array so it'd appear on [components catalog page](https://style.monday.com/?path=/docs/catalog--catalog)

**Comment by Suraj-Bhandarkar-S** [comment]
@SergeyRoyt  can I take this up? if its still pending?

**Comment by talkor** [comment]
Sure, it's yours @Suraj-Bhandarkar-S, thanks!

**Comment by YossiSaadi** [comment]
Solved in #1892
