### ISSUE TITLE
Related components: fix < Steps />, < Tipseen /> - make examples clickable

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/monday-ui-react-core#1849]
[The task is relevant for external contributors]
[(Monday ticket - Steps)](https://monday.monday.com/boards/3532714909/pulses/5506758604)
[(Monday ticket - Tipseen)](https://monday.monday.com/boards/3532714909/pulses/5506760972)

- Make `StepsDescription` component example clickable on the [components catalog page](https://style.monday.com/?path=/docs/catalog--catalog) - same as on the [story page](https://style.monday.com/?path=/docs/data-display-steps--docs)
<img width="355" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/104433616/5bfc0491-2094-4beb-b652-10b161523be3">

- Make `TipseenDescription` component example clickable on the [components catalog page](https://style.monday.com/?path=/docs/catalog--catalog) - same as on the [story page](https://style.monday.com/?path=/docs/popover-tipseen--docs) - `Tipseen with wizard`
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/a3d86beb-482a-4e66-89f0-d9eb1e0dd4ee)

**Comment by PraveenShinde3** [comment]
Can I work on this?

**Comment by PraveenShinde3** [comment]
@SergeyRoyt i have attached a video please see if this is what required to fix this issue?

[4077d6c2-77a6-4f71-8d52-d26c0c6f42e3.webm](https://github.com/mondaycom/monday-ui-react-core/assets/107350270/2513980a-79ba-492c-9b84-3eae4e0b82df)

**Comment by SergeyRoyt** [comment]
Hey, @PraveenShinde3!
You are more than welcome to work on this, we'd really appreciate your input!
And yes, that's exactly that's needed to be done! 🙂 + same for `Tipseen` 
So, feel free to open the PR and I'll do the review 😉

**Comment by PraveenShinde3** [comment]
@SergeyRoyt I have opened a PR #1851  to fix this please review and let me know if any changes in required.
