### ISSUE TITLE
docs: RelatedComponents - < Button /> related components list - replace < Chips /> with < Badge />

### ISSUE THREAD

**Issue by shaharzil** [mondaycom/monday-ui-react-core#1878]
[The task is relevant for external contributors]
[(Monday ticket)](https://monday.monday.com/boards/3532714909/pulses/5578532915)

Fix the [<Button />](https://style.monday.com/?path=/docs/buttons-button--docs)  component’s "Related components" list by replacing `<Chips />` with `<Badge />`

<img width="640" alt="large-image" src="https://github.com/mondaycom/monday-ui-react-core/assets/33456543/02f449e5-97a8-4d4c-87be-c47badb5fcbf">

**Comment by Suraj-Bhandarkar-S** [comment]
Hi I am not sure what is expected however from what I see, the changes are already present :thinking: 
![image](https://github.com/mondaycom/monday-ui-react-core/assets/42907076/2a78b2fc-c693-4ebb-b84a-0b43f1199cae)

**Comment by shaharzil** [comment]
Hi, @Suraj-Bhandarkar-S seems like you are right and this is not relevant anymore :)
I will close this issue and will open a few new ones soon. thank you!
