### ISSUE TITLE
fix: typo and warnings <Label/> <OtherContributorsList />

### ISSUE THREAD

**Issue by Suraj-Bhandarkar-S** [mondaycom/monday-ui-react-core#1879]
![Typo in labels](https://github.com/mondaycom/monday-ui-react-core/assets/42907076/c17aada7-6f6c-4892-b41f-2b7c63dce934)
Typo in Label

Warning in Home Page for runtime.js:92 Warning: validateDOMNesting(...): p tag cannot appear as a descendant of p tag.
![warningHomePage](https://github.com/mondaycom/monday-ui-react-core/assets/42907076/41781d21-25a2-4d83-92dd-9f8f9c58a7ce)

Warning in Label Component Doc's List misting key Prop
runtime.js:92 Warning: Each child in a list should have a unique "key" prop.
![issue-Label](https://github.com/mondaycom/monday-ui-react-core/assets/42907076/5f94eea9-4962-48a0-8b3a-94a649fd044d)

**Comment by Suraj-Bhandarkar-S** [comment]
I have already fixed these will submit PR shortly

**Comment by talkor** [comment]
Hi @Suraj-Bhandarkar-S! Thanks for your attention and fixes! If you don't mind, in the future, it would be really helpful if you could create a separate issue for each problem to better track each problem and its fix. Thanks!

**Comment by Suraj-Bhandarkar-S** [comment]
@talkor Sure ^^ will keep that in mind. Thank you!!
