### ISSUE TITLE
docs: change font weights in examples

### ISSUE THREAD

**Issue by talkor** [mondaycom/monday-ui-react-core#1881]
In the [Typography](https://style.monday.com/?path=/docs/foundations-typography--docs) page, in the `Text1 - 16px` and `Text2 - 14px` examples, the code snippet of the mixin shows the wrong font weight for each line. It should match the font weight described in the first column.
![image](https://github.com/mondaycom/monday-ui-react-core/assets/18269880/aef646db-860a-484a-9fc0-58211e865382)

**Comment by prathamnagpure** [comment]
Can I work on this?
If I am not wrong changes should be made in [tography.mdx](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/storybook/stand-alone-documentaion/typography/typography.mdx) 

Thanks, 
Pratham

**Comment by talkor** [comment]
> Can I work on this?
> 
> If I am not wrong changes should be made in [tography.mdx](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/storybook/stand-alone-documentaion/typography/typography.mdx) 
> 
> 
> 
> Thanks, 
> 
> Pratham

Sure, @prathamnagpure, it's yours, thanks you!
