### ISSUE TITLE
Dropdown components don't fill width when using flex row

### ISSUE THREAD

**Issue by JoshGuyer** [mondaycom/monday-ui-react-core#1889]
The dropdown component doesn't fill the width of the flex layout when align="Stretch" and direction="Row"

I think this is more of an issue with the Dropdown component width not adjusting to the width of the text inside it.

**Comment by talkor** [comment]
Hi @JoshGuyer, thanks for reporting! Can you please attach a code snippet that reproduces the issue? Preferably  in a [code sandbox](https://codesandbox.io/p/sandbox/quizzical-ride-7l47dc) or similar. Also please mention which `monday-ui-react-core` version you're using.
Thanks!

**Comment by JoshGuyer** [comment]
I am unable to get the code sandbox working, but here is the code for the component and what it displays.

`<Flex direction="Row" align="Stretch">
      <Dropdown placeholder="Product 1" />
      <Dropdown placeholder="Product 2" />
    </Flex>`

![image](https://github.com/mondaycom/monday-ui-react-core/assets/52925495/bc8e171c-bbbc-4b13-a0f0-3e13c2eed01c)

**Comment by talkor** [comment]
Thanks for the info @JoshGuyer ! 
Looks like it's a bug in `react-select@3.2.0` which we use in the `Dropdown` component.
See it [reproduced](https://stackblitz.com/edit/stackblitz-starters-3pi5cw) in `react-select@3.2.0`, and [fixed](https://stackblitz.com/edit/stackblitz-starters-6rohe6) in `react-select@5.8.0`.

We will be working on upgrading it internally but in the meantime you can set a min-width for the dropdowns, or if you want to flex them to the entire block you can set `flex: 1`. Let me know if that fixes it for now.

Thanks for reporting!

**Comment by talkor** [comment]
> Setting the flex to 1 works, thanks!
> 
> `<div style={{flex: 1}}> <Dropdown placeholder="Product 2"/> </div>`

Cool, no problem. If you want you can also provide the Dropdowns a `className` and give them flex:1, should also work without the extra div
