### ISSUE TITLE
[Bug]: ^2.92.2 is not installing with the dist folder inside the node_modules.

### ISSUE THREAD

**Issue by nativedone** [mondaycom/monday-ui-react-core#1957]
### Vibe version

^2.92.2

### Describe the bug

^2.92.2 is not installing with the **dist** folder inside the node_modules.

Then we are unable to import any components because the entry point of this library is:

```
{
  "name": "monday-ui-react-core",
  "version": "2.92.2",
  "description": "Official monday.com UI resources for application development in React.js",
  "main": "./dist/main.js",

...
}
```

### Expected behavior

Be able to import components like:

import { Dropdown } from "monday-ui-react-core";

### Steps to reproduce

npm i monday-ui-react-core

import { Dropdown } from "monday-ui-react-core";

### System Info

```shell
System:
    OS: macOS 12.7
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Memory: 22.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.volta/tools/image/node/20.9.0/bin/node
    Yarn: 4.0.1 - ~/.volta/tools/image/yarn/4.0.1/bin/yarn
    npm: 10.1.0 - ~/.volta/tools/image/node/20.9.0/bin/npm
    pnpm: 8.10.2 - ~/.volta/bin/pnpm
    Watchman: 2023.04.10.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 121.1.62.156
    Chrome: 121.0.6167.160
    Safari: 17.0
  npmPackages:
    monday-ui-react-core: ^2.92.2 => 2.92.2
    react: ^18 => 18.2.0
```

### Additional context, Screenshots

<img width="844" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/20998754/fd11dd0e-646a-4d06-9546-09726b47b690">

**Comment by talkor** [comment]
Hey @nativedone! Thank you for reporting this issue! We are on it, sorry about that, we will release a new version with a fix soon. In the meantime you can use `2.92.1` (fixed).
Thanks!

**Comment by shaharzil** [comment]
Hey @nativedone
The issue was fixed, please upgrade to our latest version  (`2.92.4` ) thanks!
