### ISSUE TITLE
[Bug]: Tabs - line of active tab is under expected position

### ISSUE THREAD

**Issue by ramarm** [mondaycom/monday-ui-react-core#1992]
### Vibe version

2.93.0

### Describe the bug

When using the TabList component, the blue line is under the expected position. You can see in the attached video.

### Expected behavior

The line should be 8 px above 4px margin in top + bottom.

### Steps to reproduce

Just use the TabList. You can see that the inner <a> tag have 4px padding in my environment while in the playground it is 0.

### Reproduction example link

https://www.loom.com/share/a2c457044b444fda9d5a340f6d215f24?sid=76cec034-b9ab-4ea4-a1a1-8000c3f3c571

### System Info

```shell
Chrome version 122, windows 11
```

**Comment by ramarm** [comment]
Hey @talkor 
This but is also fixed when adding `* { box-sizing: border-box; }`
Thanks

**Comment by YossiSaadi** [comment]
@ramarm Thanks for reporting!
linking those issues to each other and resolving them for now
we're discussing whether we should export the library with default `box-sizing` or not, but anyway this is a breaking change and would only occur in next major

related #2001
