### ISSUE TITLE
[Bug]: Editable heading type is not taken

### ISSUE THREAD

**Issue by ramarm** [mondaycom/monday-ui-react-core#1998]
### Vibe version

2.94.0

### Describe the bug

Hey, I try to use the editable heading and I tried to use the type and weights and change it to TEXT1 or other than normal it works only in edit state.
Attached a video showing the behaviour

### Expected behavior

Attached video - https://www.loom.com/share/087d5865a518495197886d91dd8a9e3b?sid=97295544-207b-4834-8bc0-e05d68f903c8

### Steps to reproduce

Just add an editable text and try to change it to type "TEXT2" and try to change the weight

### Reproduction example link

https://www.loom.com/share/087d5865a518495197886d91dd8a9e3b?sid=97295544-207b-4834-8bc0-e05d68f903c8

**Comment by YossiSaadi** [comment]
Hey @ramarm, thanks for reporting!
I was not able to reproduce:
https://stackblitz.com/edit/vibe-bug-report-45lec6

Can you create a reproducible example please in a clean environment?

**Comment by ramarm** [comment]
Hey @YossiSaadi ,
I created a simple example - https://github.com/ramarm/vibe-bug
Clone the code and start it. You should see the problem

**Comment by YossiSaadi** [comment]
> Hey @YossiSaadi , I created a simple example - [ramarm/vibe-bug](https://github.com/ramarm/vibe-bug) Clone the code and start it. You should see the problem

this repo does not seem to include monday-ui-react-core or EditableHeading

**Comment by HermanBide** [comment]
has this been fixed?

**Comment by talkor** [comment]
@ramarm I can't reproduce it either with your given example

**Comment by ramarm** [comment]
@talkor I run on windows with google chrome v122. I am available for a meeting to show you the issue if needed

**Comment by shaharzil** [comment]
Hi @ramarm, the issue was fixed and merged to the master 😄 
I'll let you know once we will release a new version with the fix.

**Comment by talkor** [comment]
Released in [2.98.0](https://github.com/mondaycom/monday-ui-react-core/blob/master/packages/core/CHANGELOG.md#2980-2024-03-19)
