### ISSUE TITLE
[Bug]: MultiStepIndicator styling problems

### ISSUE THREAD

**Issue by ramarm** [mondaycom/monday-ui-react-core#2001]
### Vibe version

2.94.0

### Describe the bug

When using the compact version of the MultiStepIndicator I found 2 bugs
1. When moving the cursor on the numbers the text moves
2. The lines are not aligned to the center of the text

### Expected behavior

1. the line supposed to be in the center
2. The text shouldn't move

### Steps to reproduce

Example is here - https://github.com/ramarm/vibe-bug
video showing the problem - https://www.loom.com/share/74eb3a6670554b3695f3a371726e23ba

### Reproduction example link

https://github.com/ramarm/vibe-bug

**Comment by talkor** [comment]
Hi @ramarm ! Thanks for reporting, I cannot reproduce the issue, see this [stackblitz](https://stackblitz.com/edit/vibe-bug-report-wquwlt?file=src%2FApp.tsx). Please check if any custom global styles affect the style of the vibe components you use (maybe style on `div` elements etc)

**Comment by talkor** [comment]
Thanks for the additional info! Vibe assumes the application it's being used in has a `* { box-sizing: border-box; }` rule as it's considered to be the standard. It's not documented but will be soon 🙏🏼 

This is why removing the style file in the reproduction actually reproduces this issue. I suggest to add this rule in the root stylesheet of your application (highly recommended), or just add the box-sizing property in the MultiStepIndicator component using the `className`, depending on your needs.

Thanks @ramarm!

**Comment by ramarm** [comment]
Hey @talkor ,
Thank you for this tip. This tip did solve one of the issues (The moving text) but the lines are still not aligned with the text in my environment.
Also - If the `* { box-sizing: border-box; }` is required for good styling with vibe, why won't you put it on your css file?

**Comment by talkor** [comment]
Thank @ramarm ! A fix is on the way for the alignment of the dividers as well

**Comment by talkor** [comment]
> Also - If the `* { box-sizing: border-box; }` is required for good styling with vibe, why won't you put it on your css file?

We will include this rule in the next major version for all components to avoid similar issue, thanks for the feedback!

**Comment by talkor** [comment]
Fixed in [v2.98.3](https://github.com/mondaycom/monday-ui-react-core/blob/master/packages/core/CHANGELOG.md#2983-2024-03-24)
