### ISSUE TITLE
[Bug]: hideCloseButton in modal - not working

### ISSUE THREAD

**Issue by ramarm** [mondaycom/monday-ui-react-core#2034]
### Vibe version

2.94.0

### Describe the bug

In the documentations there is a prop in order to hide the close button in the modal.
This props is not handled in the code - It looks like there is a comment to remove in the next breaking change.
That mean there is no way to remove or change the position of this icon.
My problem is that this button is not in the right position...

### Expected behavior

The ability to remove or change position of the close button

### Steps to reproduce

Add hideCloseButton to the <Modal> or <ModalHeader> and it work have any affect

**Comment by talkor** [comment]
Thanks @ramarm for bringing that up, this is a UX consideration as users should always be able to close modals (escape route), as stated in the code we will remove it in the next version, sorry for the confusion for now

**Comment by ramarm** [comment]
@talkor I agree with the UX consideration - But in my case I just want to change the position of the close button so it will be a bit higher
Maybe you can export a className that we can apply on the closeButton?

**Comment by talkor** [comment]
> @talkor I agree with the UX consideration - But in my case I just want to change the position of the close button so it will be a bit higher Maybe you can export a className that we can apply on the closeButton?

Changing the position of the close button creates inconsistency, why do you want to change it?
