### ISSUE TITLE
Add role "combobox" to Combobox component 

### ISSUE THREAD

**Issue by hadasfa** [mondaycom/monday-ui-react-core#253]
Add role: "combobox" to the input element of the Combobox component

**Comment by vivek32ta** [comment]
Hi @hadasfa, I'd love to take this up

**Comment by hadasfa** [comment]
@vivek32ta Sure :) Let's do this. I'll check your PR when it's ready.

**Comment by hadasfa** [comment]
@vivek32ta vivek32ta do you still working on this PR?

**Comment by aayushbisen** [comment]
Combo box component renders a Search input which has a default role value `search`.

Do we need to customize the Search prop structure to give the required role in Combo box?
