### ISSUE TITLE
AttentionBox: Change the role of the component to alert instead of complementary

### ISSUE THREAD

**Issue by hadasfa** [mondaycom/monday-ui-react-core#256]
AttentionBox: Change the role of the  "AttentionBox" component to alert instead of complementary.

**Comment by Mihir50** [comment]
> @hadasfa can you assign me this issue

Hey I was working on this :(

**Comment by Dev5902** [comment]
@Mihir50 I am also new to open source but I know that until and unless an issue is not assigned to anyone it can be worked upon by anyone who wants to work on it. I am very close to solving this issue.

**Comment by hadasfa** [comment]
solved by @Dev5902 #262
