### ISSUE TITLE
Square Button - Spinner not shown in mobile browsers in loading state

### ISSUE THREAD

**Issue by eranh** [mondaycom/monday-ui-react-core#33]
When button is in loading state - it shrinks but no spinner is shown. Works fine in mobile emulators on desktop
Talked to Orr about it.

**Comment by sanjaykumaryada** [comment]
Hi @eranh @orrgottlieb  can you assign this to me? can you post screenshots

**Comment by orrgottlieb** [comment]
@SergeyRoyt @YossiSaadi

**Comment by SergeyRoyt** [comment]
Didn't reproduce for me on mobile browser - closing the issue
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/41f9e9a0-2c8f-45f6-bc24-f3d37fc500f3)
