### ISSUE TITLE
Declaration File for typescript

### ISSUE THREAD

**Issue by hswimmer** [mondaycom/monday-ui-react-core#353]
For using this package with typescript, can you add declaration files

**Comment by orrgottlieb** [comment]
Hi @hswimmer , thank you for that request.
We plan on adding decleration files in the start of 2022

**Comment by jolo-dev** [comment]
Is that still planned?

**Comment by nadav-dav** [comment]
Bump

**Comment by orrgottlieb** [comment]
Hi all in this thread, we had a change of priorities inside the company,
We will focus in Q3 on the following things

1. Typescript
2. Migrating our component css to css modules
@nadav-dav @jolo-dev @hswimmer

**Comment by hadasfa** [comment]
Hello everyone, following what @orrgottlieb wrote, we have started to invest efforts in our team on converting monday-ui-react-core from Javascript to Typescript. 
We will add a declaration type for all our components as part of these efforts. The file will be accessible for anyone using our package but we will add it to the package.json "types" field after we will finish the conversion.
The first pr, which is related to the typescript migration effort, will be merged to master at the beginning of this week:
https://github.com/mondaycom/monday-ui-react-core/pull/794


@nadav-dav @jolo-dev @hswimmer

**Comment by orrgottlieb** [comment]
@hswimmer closing this issue as we started our migration to typescript
