### ISSUE TITLE
Dropdown: onOptionRemove prop is missing in the documentation

### ISSUE THREAD

**Issue by fredunikoo** [mondaycom/monday-ui-react-core#497]
Hi,

I noticed the Dropdown component documentation is lacking info on the onOptionRemove prop. It took me quite some time to figure out how to remove a single element when working with a multi Dropdown controlled component. When checking out the source, I found the existence of the onOptionRemove prop.

Thank you for al the work done in this library, it is so much fun working with it :).

**Comment by hadasfa** [comment]
Hey, thank you so much on your feedback! Following your request, we added the onOptionRemove to the dropdown props docs.
