### ISSUE TITLE
Feature request - Expose storybook utils as a storybook addon

### ISSUE THREAD

**Issue by saaryab** [mondaycom/monday-ui-react-core#526]
Hi all and thanks for the inspiring work on your Design System, as well as for making this public so we can all appreciate it.

I am working on building a Design System for my company using our existing components and because I love your style I was wondering if you might think of separating the storybook functions and components from the actual component library so that others could use that setup as a storybook addon. If that's too much to ask for, maybe just exposing those in an alternate build would also be useful.

For now I forked your repo and changed the webpack entry point to include the `src/storybook` directory to get access to the storybook components but it would be great if you supported this.

Thanks!

**Comment by SergeyRoyt** [comment]
Hey, @saaryab !
Sorry, for the long response, but I'm happy to share with you that we've extracted components, which we are using to build storybook, into a separate open-source package https://github.com/mondaycom/vibe-storybook-components and we'll be happy if you find it useful ❤️

**Comment by saaryab** [comment]
Thanks! I'll take a look and hopefully make use of this new package!
