### ISSUE TITLE
Textwithhighlight - Feature request - Support custom tags and classnames 

### ISSUE THREAD

**Issue by nunibaranes** [mondaycom/monday-ui-react-core#559]
I'm using the [Textwithhighlight](https://style.monday.com/?path=/docs/text-textwithhighlight--overview) component, and I'd like to override/add the highlight-text element style.

1. Is it possible to support an additional className for the `highlight-text` element?
2.  Is it is possible to support rendering different HTML tags? like in this [library](https://www.npmjs.com/package/react-highlight-words), I can see you can use `highlightTag` prop to render another Html tag, for example `<strong>` instead of `<em>`?

**Comment by orrgottlieb** [comment]
Added from 1.44.0
