### ISSUE TITLE
This component is very beautiful, what is it called? Are there plans to open source it?

### ISSUE THREAD

**Issue by cjd6568358** [mondaycom/monday-ui-react-core#572]
![image](https://user-images.githubusercontent.com/3970494/157032917-ae8851c4-0e78-4c93-9777-f8fef4c30333.png)

**Comment by MosheZemah** [comment]
Hi @cjd6568358 , thank you for reaching out. 
Currently this "Group header" is not part of our open source code. It is part of our inner monday.com code, and there are no plans to release it to open source in the near future. 
Thank you.
