### ISSUE TITLE
Automations same as monday.com

### ISSUE THREAD

**Issue by kinju4374** [mondaycom/monday-ui-react-core#685]
Hi,

I want to create an automation UI the same as monday.com and I was exploring your API. I was successfully able to install **monday-ui-react-core** but I am getting errors when I run storybook. Could you please help me how to resolve the storybook error? Also, are there any initial simple examples to run and check simple UI with your API?

**Comment by orrgottlieb** [comment]
hi @kinju4374 , can you please share the errors here ?

**Comment by kinju4374** [comment]
Hi @orrgottlieb ,

I installed storybook using npm and after that I am getting a new error

![image](https://user-images.githubusercontent.com/17248153/170487657-4600ad63-4f9d-4b1d-b9ec-ff5028024b70.png)

I have added the following in package.json

![image](https://user-images.githubusercontent.com/17248153/170487793-44f42ca3-29f2-4f5b-b0ce-3d892b2623ec.png)

**Comment by orrgottlieb** [comment]
Hi @kinju4374 , thank you for posting this issue.
it look like you are trying to run your own storybook, please notice that storybook is a tool which helps develop component in a very efficient way.

* if you want to use storybook to develop your own local ui i suggest you go see the storybook docs https://storybook.js.org/docs/react/get-started/install
* if you want to see our storybook locally you can clone our repo, run `npm i` and then `npm run storybook` 

sorry for the delay

**Comment by orrgottlieb** [comment]
Hi @kinju4374, 
Can i please close this issue ?
