### ISSUE TITLE
Adding validation with { status: "error" } adds the error text but not the red border

### ISSUE THREAD

**Issue by udidoron** [mondaycom/monday-ui-react-core#75]
Checked on `monday-ui-react-core@0.0.80.`

### Example code:

```jsx
const validation = { status: "error", text: "Some error text" }
    return (
          <TextField
            {...textFieldProps}
            validation={validation}
          />
    );
```

### Expected result
The `TextField` will be rendered with a red border and a red error text.

### Actual result
Only the red error text is rendered.

![image](https://user-images.githubusercontent.com/6594051/109702813-65a00580-7b9d-11eb-9931-cf8df5f74052.png)

**Comment by orrgottlieb** [comment]
@udidoron this works fine in our storybook, can you please provide more details - like if the CSS is overridden in your app?

**Comment by hadasfa** [comment]
Can I close this one? @orrgottlieb @udidoron
