### ISSUE TITLE
Disabled button no longer showing a not-allowed cursor

### ISSUE THREAD

**Issue by fatihict** [mondaycom/monday-ui-react-core#774]
Due to `pointer-events: none;` `cursor: not-allowed` is no longer working

**Comment by orrgottlieb** [comment]
Thank you,
We will investigate

**Comment by vczb** [comment]
Hi I want to work on it 

cc: @orrgottlieb @hadasfa

**Comment by orrgottlieb** [comment]
@vczb go ahead

**Comment by vczb** [comment]
Hi @orrgottlieb , I already did submit my PR and I trying to understand what is missing to complete the CI. Can you help me with that?

Thanks in advance
