### ISSUE TITLE
React 18 issue

### ISSUE THREAD

**Issue by infonexage** [mondaycom/monday-ui-react-core#783]
Am trying to implement with React 18, Is this will support ?? because this developed in react 16.
I'm facing many issues while adding the components with storybook styles. Kindly assist

**Comment by orrgottlieb** [comment]
Hi @infonexage , can you please share some of the issues that you are facing,
* What are the errors?
* Where are you facing them ?

Code example or a demo repo would be appreciated as well

**Comment by infonexage** [comment]
Actually am new for react, I'm trying to develop same like monday.com website with my custom data. I'm using this package to make development. 

<div className={classes["leftpane-workspaces-section"]}>
      <span className={classes["leftpane-workspaces-title"]}>Workspace</span>
      <span className={classes["leftpane-workspaces-options"]}>
        <div className={classes["leftpane-workspaces-description"]}>
        <Avatar size={Avatar.sizes.SMALL} text="W" backgroundColor={Avatar.colors.INDIGO} isSquare />
        Workspace name
        </div>
        <Icon className={classes["leftpane-workspaces-options-icon"]} icon={DropdownChevronDown} />
      </span>
      <List>
        <ListItem>
          <ListItemIcon icon={Add} />
          Add
        </ListItem>
        <ListItem>
          <ListItemIcon icon={Filter} />
          Filter
        </ListItem>
      </List>
       </div>
       
In above code "classes not defined". But still installed and included classname plugins. because of this styles rendering errors 
Is there any setup documentation available. 

Thanks in advance

**Comment by orrgottlieb** [comment]
@infonexage it looks like you are missing an import of classes (maybe from the css module file)
