### ISSUE TITLE
Accordion Typescript conversion 

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#891]
### TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Accordion.jsx
- [ ] accordionItem-tests.jest.js
- [ ] accordion.interactions.js
- [ ] AccordionItem.jsx

Good luck!

**Comment by SumeetHaryani** [comment]
Hey @orrgottlieb, I would like to work on this issue

**Comment by orrgottlieb** [comment]
@SumeetHaryani go ahead! 
please notice that i've updated the issue description

**Comment by SumeetHaryani** [comment]
yup, Thanks :)

**Comment by inovux** [comment]
is this available to work on or is it in progress :P ?

**Comment by orrgottlieb** [comment]
Hi @SumeetHaryani are you working on this one, as other people might want to take this one as well

@inovux will update you here soon 🙏

**Comment by inovux** [comment]
@orrgottlieb okay tnx !

**Comment by SumeetHaryani** [comment]
@orrgottlieb you can assign this issue to @inovux. As I am currently working on other issues

**Comment by orrgottlieb** [comment]
@inovux you got this!

@SumeetHaryani thank you

**Comment by hadasfa** [comment]
Hey @inovux !  Are you still working on this issue?

**Comment by hadasfa** [comment]
@inovux Thank you for the update. I will remove you from this issue assigns for making this available for anyone who want to take it.

**Comment by hadasfa** [comment]
@aayushbisen You got this!
