### ISSUE TITLE
AttentionBox Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#892]
### TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] AttentionBox.jsx
- [ ] attentionBox-tests.jest.js
- [ ] attentionBox-snapshot-tests.jest.js

Good luck!

**Comment by SumeetHaryani** [comment]
@orrgottlieb I would like to work on this issue as well

**Comment by orrgottlieb** [comment]
@SumeetHaryani you got it!
thanks and good luck

**Comment by SumeetHaryani** [comment]
@orrgottlieb It will require me to migrate IconButton to Typescript as well.
Should I update it?

**Comment by orrgottlieb** [comment]
@SumeetHaryani you may 🙏

**Comment by hadasfa** [comment]
@SumeetHaryani We would love to merge your PR but right now we have a conflict there. Can you please resolve it and we will be able to accept it and mark this issue as "hacktoberfest accepted".
