### ISSUE TITLE
Avatar Component Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#893]
### TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Avatar.jsx
- [ ] AvatarBadge.jsx
- [ ] avatar.jest.js
- [ ] AvatarConstants.jsx
- [ ] AvatarContent.jsx

Good luck!

**Comment by SumeetHaryani** [comment]
@orrgottlieb I would like to work on this issue as well
Thanks :)

**Comment by orrgottlieb** [comment]
@SumeetHaryani you got it!
