### ISSUE TITLE
Banner Component Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#894]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Banner.jsx
- [ ] banner.jest.js
- [ ] BannerConstants.js

Good luck!

**Comment by suvnshr** [comment]
Hi @orrgottlieb, I would like to pick this up.

I would be following the patterns used in the .tsx and .ts files already present in the project.

**Comment by orrgottlieb** [comment]
Hi @suvnshr go for it!

**Comment by orrgottlieb** [comment]
Hi @suvnshr thank you for the comments

1. please fix the way that you suggested adding the `React.Element` type, you may (if you want) replace the `string` type with it
2. awesome solution, go for it!
3. we are using `HTMLElement quite a lot, can you please add a type there that it is either `HTMLElement | SVGElement ` in the types folder [here](https://github.com/mondaycom/monday-ui-react-core/tree/master/src/types), thank you

As this migration process is a work in progress you can fix types according to new needs

**Comment by suvnshr** [comment]
Ok sure. Will do the changes.

Thanks!
