### ISSUE TITLE
Checkbox Component Typescript converstion

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#895]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Checkbox.js
- [ ] useSupportFirefoxLabelClick.jsx
- [ ] checkbox-tests.jest.js
- [ ] checkbox-snapshot-tests.jest.js

Good luck!

**Comment by Rahul-Palahwat** [comment]
Hey @orrgottlieb it would be great if you assign this issue to me

**Comment by orrgottlieb** [comment]
@Rahul-Palahwat go for it!

**Comment by hadasfa** [comment]
Hey @Rahul-Palahwat ! Are you still working on this issue?

**Comment by Rahul-Palahwat** [comment]
Hey @hadasfa so sorry for delay. Please assign this issue to anyone else

**Comment by suvnshr** [comment]
Hey @orrgottlieb can I pick this up?

**Comment by hadasfa** [comment]
@suvnshr You got this! Good luck 🥇

**Comment by suvnshr** [comment]
Thanks

**Comment by hadasfa** [comment]
@suvnshr Hey are you still working on this issue?

**Comment by suvnshr** [comment]
yes, got a busy schedule as of today...will start working on it tomorrow onwards.

**Comment by suvnshr** [comment]
@orrgottlieb I have a doubt

[Here](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/components/Checkbox/__tests__/checkbox-tests.jest.js#L11), `isFirefox` is imported from [user-agent-utils](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/utils/user-agent-utils.ts), where it is defined as a simple function. 

but `isFireFox` is also calling a jest function in the same file [here](https://github.com/mondaycom/monday-ui-react-core/blob/master/src/components/Checkbox/__tests__/checkbox-tests.jest.js#L174).

I'm confused, what type I should assign to `isFireFox`?

are they supposed to be 2 different variables? one for calling the jest function, and one for that user-agent function?

**Comment by kabhamo** [comment]
Hi @orrgottlieb, @hadasfa,
I hope you are doing well.
I noticed that `useSupportFirefoxLabelClick.jsx` is still not converted to typescript.
I have a **PR** ready to be created with relevant changes for the **useSupportFirefoxLabelClick hook file** 
Also, I have tested the functionality and it works as needed, I would be so happy to create a PR for it.
Let me know if it is still relevant.

**Comment by orrgottlieb** [comment]
Hi @kabhamo ,
Thanks! going over the PR now

**Comment by lidoravitan** [comment]
is it still opened?

**Comment by orrgottlieb** [comment]
Hi @lidoravitan, this is done, but we have another great option for you if you want `ResponsiveList` https://github.com/mondaycom/monday-ui-react-core/blob/master/src/components/ResponsiveList/ResponsiveList.jsx

if you want i can create an issue for you and assign it to you ?

**Comment by lidoravitan** [comment]
sure let me know what needs to be done on `ResponsiveList`

**Comment by lidoravitan** [comment]
@orrgottlieb any update?
