### ISSUE TITLE
Divider Component Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#896]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Divider.jsx
- [ ] DividerConstants.js
- [ ] divider.jest.js

Good luck!

**Comment by aayushbisen** [comment]
Can I work on this issue? @orrgottlieb

**Comment by orrgottlieb** [comment]
@aayushbisen of-course you can :) 
assigned this to you 🙏

**Comment by aayushbisen** [comment]
I have a doubt
In `Divider.jsx` is the classname prop optional?

**Comment by orrgottlieb** [comment]
@aayushbisen yes

**Comment by aayushbisen** [comment]
First PR of Hacktoberfest 2022 ✅
