### ISSUE TITLE
Counter Components Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#899]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Counter.jsx
- [ ] CounterConstants.js
- [ ] counter-tests.jest.js
- [ ] counter-snapshot-tests.jest.js

Good luck!

**Comment by a11rew** [comment]
I'd like to take this up @orrgottlieb

**Comment by orrgottlieb** [comment]
You got it! @a11rew

**Comment by orrgottlieb** [comment]
@a11rew thank you, @laviomri will do the review!
