### ISSUE TITLE
DialogContentContainer Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#900]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] DialogContentContainer.jsx
- [ ] dialogContentContainer.jest.js

Good luck!

**Comment by vishal-codes** [comment]
Hey @orrgottlieb I am beginner in typescript and I would like to work on this issue.

**Comment by orrgottlieb** [comment]
Hey @vishal-codes , you got this!
good luck

**Comment by hadasfa** [comment]
@vishal-codes hey! are you still working on this issue?

**Comment by hadasfa** [comment]
@vishal-codes Thank you for your contribution! I am also a maintainer in vibe design system :)
I reviewed your PR, did you have a chance to read my comments?

**Comment by vishal-codes** [comment]
> @vishal-codes Thank you for your contribution! I am also a maintainer in vibe design system :) I reviewed your PR, did you have a chance to read my comments?

I am extremely sorry, I wasn't able to work on requested changes as I was indulged in my exams but I assure you that I'll work and update about it in the next 24 hours.

**Comment by hadasfa** [comment]
there is any news regarding the PR? @vishal-codes

**Comment by vishal-codes** [comment]
> there is any news regarding the PR? @vishal-codes

Yes I have completed the requested changes. Commit - https://github.com/mondaycom/monday-ui-react-core/pull/933/commits/c15006bfaa1e295daee8af20883d89018157d138

**Comment by hadasfa** [comment]
Thank you so much! I am approving this right now and adding the hacktoberfest accepted tag

**Comment by vishal-codes** [comment]
> Thank you so much! I am approving this right now and adding the hacktoberfest accepted tag

Thank you for helping me by providing detailed review.😀
