### ISSUE TITLE
Link Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#903]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Link.jsx
- [ ] LinkConsts.js
- [ ] link-snapshot-tests.jest.js
- [ ] link-tests.jest.js

Good luck!

**Comment by ercusz** [comment]
I'd like to work on this @orrgottlieb

**Comment by orrgottlieb** [comment]
You got it @ercusz

**Comment by ercusz** [comment]
From current code in [Link.jsx#L32](https://github.com/mondaycom/monday-ui-react-core/blob/4f49d2cfc703c1b2f427d74e6f34abfcabc0c8c0/src/components/Link/Link.jsx#L32) the `backwardCompatibilityForProperties` function  requires 2 arguments, but only one argument is passed from that line. 
Do you have any idea how to migrate that line? @orrgottlieb

**Comment by orrgottlieb** [comment]
Make the second argument optional in the backwardCompatibilityForProperties function

**Comment by orrgottlieb** [comment]
@ercusz thanks! merged and approved, closing this issue with `hacktoberfest-accepted` tag!
