### ISSUE TITLE
RadioButton Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#904]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] RadioButton.jsx
- [ ] RadioButtonConstants.js
- [ ] radioButton-snapshot-tests.jest.js
- [ ] radioButton-tests.jest.js

Good Luck!

**Comment by Suman94310** [comment]
I would like to work on this @orrgottlieb.

**Comment by orrgottlieb** [comment]
yes go for it! @Suman94310

**Comment by Suman94310** [comment]
@orrgottlieb I have created a pull request for this.

**Comment by orrgottlieb** [comment]
@Suman94310 thank you very much, if you have any comments or sugegstions about this package please let me know 🙏
