### ISSUE TITLE
Refable Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#905]
https://monday.monday.com/boards/3532714909/pulses/5424768688

TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Refable.jsx

Good Luck

**Comment by chinmaym07** [comment]
Hey @orrgottlieb . Can I work on this issue ?

**Comment by orrgottlieb** [comment]
Sure @chinmaym07 go for it!

**Comment by hadasfa** [comment]
Hey @chinmaym07 ! Are you still working on this issue?

**Comment by hadasfa** [comment]
@chinmaym07 Hey, I am one of Vibe design system maintainers.
I unsassign you from this issue due to lack of activity, if there is any updates or you got back to this issue please let me know.

**Comment by naorpeled** [comment]
Hey,
may I be assigned to this issue?

**Comment by orrgottlieb** [comment]
Hi @naorpeled you got it!

**Comment by SergeyRoyt** [comment]
Ready for anyone willing to take it :)

**Comment by aayushbisen** [comment]
> Ready for anyone willing to take it :)

Can I work on this?

**Comment by naorpeled** [comment]
Hey @SergeyRoyt,
was planning to finish working on this after another PR of mine would be merged,
it got merged about a day ago.

Can I be re-assigned to this one?

**Comment by aayushbisen** [comment]
> Hey @SergeyRoyt, was planning to finish working on this after another PR of mine would be merged, it got merged about a day ago, sorry for the huge delay.
> 
> @aayushbisen wanna work on this one together? 😎

Sure

**Comment by SergeyRoyt** [comment]
Thanks, guys! Good luck with the issue!

**Comment by naorpeled** [comment]
Hey @aayushbisen,
do you have Discord?
if so, what's your tag?

**Comment by SergeyRoyt** [comment]
Closed thanks to @naorpeled !
