### ISSUE TITLE
Skeleton Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#908]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Skeleton.jsx
- [ ] SkeletonConstants.jsx
- [ ] skeleton-snapshot-tests.jest.js

Good Luck

**Comment by AhmedAli125** [comment]
Hey @orrgottlieb! Can you please assign this issue to me

**Comment by orrgottlieb** [comment]
Hi @AhmedAli125 you got it!

**Comment by manastelavane** [comment]
Hey @orrgottlieb ,if this issue is not assigned to anyone. Plz assign it to me.

**Comment by orrgottlieb** [comment]
Hi @AhmedAli125 are you still working on this issue?

@manastelavane will update as soon as @AhmedAli125 will answer

**Comment by hadasfa** [comment]
Hey @manastelavane, I am also a maintainer in Vibe design system. Do you still working on this issue?

**Comment by manastelavane** [comment]
I was busy with my exams. I will try to make a pr till Tomorrow.

**Comment by hadasfa** [comment]
No problem, thank you!

**Comment by manastelavane** [comment]
Hey @hadasfa ,
I want help in converting one of the proptype to interface .
Skeleton.propTypes = {
      size: PropTypes.oneOf(
    Object.values([
      ...SKELETON_ALLOWED_SIZES.RECTANGLE,
      ...SKELETON_ALLOWED_SIZES.CIRCLE,
      ...SKELETON_ALLOWED_SIZES.TEXT
    ])
   ),
}

**Comment by orrgottlieb** [comment]
@hadasfa please see question :)

**Comment by SergeyRoyt** [comment]
Completed by PR https://github.com/mondaycom/monday-ui-react-core/pull/954
