### ISSUE TITLE
Flex Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#909]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] Flex.jsx
- [ ] FlexConstants.js
- [ ] flex-snapshot-tests.jest.js

Good Luck

**Comment by piotrski** [comment]
Hey @orrgottlieb! Can you please assign this issue to me?

**Comment by orrgottlieb** [comment]
Hi @piotrski, yes you can

**Comment by hadasfa** [comment]
@piotrski  I saw that @orrgottlieb wrote some notes on your pr. Did you see them?

**Comment by SergeyRoyt** [comment]
Closed in favor of https://github.com/mondaycom/monday-ui-react-core/pull/1006
