### ISSUE TITLE
FormattedNumber TypeScript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#910]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] FormattedNumber.jsx
- [ ] FormattedNumberConsts.js
- [ ] FormattedNumberHelpers.js
- [ ] FormattedNumber.jest.js

Good Luck

**Comment by indremak** [comment]
Hi, I would like to work on this. Could you assign me?

**Comment by orrgottlieb** [comment]
@indremak you got it!
