### ISSUE TITLE
HiddenText Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#911]
TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files

- [ ] HiddenText.jsx
- [ ] hiddenText.jest.js

Good Luck

**Comment by bautistaaa** [comment]
assign to me!
