### ISSUE TITLE
ButtonGroup Typescript Migration

### ISSUE THREAD

**Issue by orrgottlieb** [mondaycom/monday-ui-react-core#922]
### TypeScript here we come!
We are migrating to typescript, we are doing so component by component

We would love some help in converting some of our component to typescript - we've created a README
https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md

in this PR we expect you to convert the following files:

- [ ] ButtonGroup.jsx
- [ ] ButtonGroupConstants.js
- [ ] ButtonWrapper.jsx
- [ ] buttonGroup-snapshot-tests.jest.js
- [ ] buttonGroup-tests.jest.js

Good Luck

**Comment by aayushbisen** [comment]
Can I work on this issue? @orrgottlieb

**Comment by orrgottlieb** [comment]
Sure @aayushbisen

**Comment by hadasfa** [comment]
Hey @aayushbisen are you still working on this?

**Comment by aayushbisen** [comment]
Yeah!

**Comment by aayushbisen** [comment]
@orrgottlieb the `icon` and `leftIcon` properites in options prop in `ButtonGroup` are `Icon` components right?

**Comment by hadasfa** [comment]
Hey @aayushbisen I am also a maintainer in Vibe design system :)
Regarding your questions:
1. Yes, icon and left icon are react components 
2. You are correct we have a typo there. You can ignore it while creating the PR (treat tooltipMoveBy like it's working and we will fix this issue in a different PR
