### ISSUE TITLE
Refactor: Make all imports follow absolute naming

### ISSUE THREAD

**Issue by suvnshr** [mondaycom/monday-ui-react-core#936]
Since the project already contains `tsconfig.json`, absolutely named imports can be used instead of relative imports.

### Current usage(relative imports)

```js
import Icon from "../../components/Icon/Icon";
```

### After using the absolute named imports
```js

import Icon from "components/Icon/Icon";
```

---

But as of now, absolutely named imports are not used everywhere in the project.

Once the migration is done,  we can ask contributors to stick to absolutely named imports only.

I am willing to pick the migration up myself.

**Comment by orrgottlieb** [comment]
@suvnshr due to internal issue, we need to use the relative imports, once we will migrate our library build to rollup we will move it to relative 🙏
