### ISSUE TITLE
Selecting and copying content of Editable heading doesn't work

### ISSUE THREAD

**Issue by ayelethol** [mondaycom/monday-ui-react-core#95]
https://user-images.githubusercontent.com/22417492/111348734-25568200-8689-11eb-83f8-7d117465bbb3.mov

In the screen recording you can see me trying to select inside the Editable heading component (and failing)
I then show how it does work in Editable input component for reference :)

**Comment by orrgottlieb** [comment]
@ayelethol fixed in version 103
